// Copyright 2018 wevet works All Rights Reserved.

#pragma once


PRAGMA_DISABLE_DEPRECATION_WARNINGS

#define BOX_HEIGHT 30
#define PTG_TEAM_ID_PLAYER 0
#define PTG_TEAM_ID_ENEMY 1
#define PTG_TEAM_ID_NPC 2
#define NO_TEAMID 255



PRAGMA_ENABLE_DEPRECATION_WARNINGS


